language: node_js
addons:
  chrome: stable
node_js:
- 10.16.3
install:
- yarn install
cache:
  directories:
  - node_modules
before_script:
  - yarn serve
  - sleep 3
script:
  - yarn build
  - CI=true yarn test
  - yarn test:e2e
